### PR TITLE
[wikidata] Fix ISNI crashing and WP parsing

### PR DESCRIPTION
**Pull request by jesus2099**
Crash bugs (2) reported and pin-pointed by DenizC and diskotechjam in
https://community.metabrainz.org/t/user-script-to-load-artist-data-from-wikipedia/86338/38?u=jesus2099

---

- WD is Wikidata
- WP is Wikipedia

---

fillISNI function crash
-----------------------

> Uncaught TypeError: Cannot read properties of undefined (reading 'parentElement')

`edit-artist.isni_codes-template` no longer exists in react version of artist edit page.

fillFormFromISNI function crash
-------------------------------

> Uncaught TypeError: Cannot read properties of null (reading 'length')

When regex does not match, it is `null`.

Fill ISNI code from WD
----------------------

This does not work on the new react version of the artist edit page. 

Reported by @zas

Fetch WD page from WP URL
-------------------------

It does no longer find WD page from WP URL. 
Probably WP pages have changed.

Reported by diskotechjam

---

Bonus: Use only UTC time functions everywhere, for consistency

### CODE REVIEW

**Comment by zas** [comment]
When an ISNI code is already there, it is now trying to add a new.

**Comment by jesus2099** [comment]
Thanks @zas for testing.
Isn't it supposed to add ISNI to a new field when there is already one?
Can't artists have several ISNI, in practice, like they can have several IPI, like recordings can have several ISRC and like works can have several ISWC?

❌ BTW I notice that I have indeed removed the 2 ways of systematic crashing the script but ISNI is no longer set at all.

❌ For example I have an artist with no ISRC and the script just adds a second empty ISNI field.

So I will fix my fix.

But please advise what should be done when:

- Artist already has a different ISNI
- Artist already has the same ISNI
- Artist has no ISNI

**Comment by zas** [comment]
> When an ISNI code is already there, it is now trying to add a new

What I meant is it tries to add the same ISNI as it was new (so it displays it as a new field, but doesn't actually add it).

About various cases:

-     Artist already has a different ISNI
Perhaps just warn, but don't add the new one, it might be an error, and we don't know where

-     Artist already has the same ISNI
Do nothing

-     Artist has no ISNI
Add the one from WD (if any, of course)

**Comment by jesus2099** [comment]
I have fixed the WP URL handling (09f3a019ca04de4bd03859e5d60e2bcc248abf40) and the actual filling of ISNI code field from WD (582de280ee6913a1527512a02462fadafba65333), in this same PR proposal.

The only problem that remains:

> MBS new react-hydrate system makes it so that script added ISNI code
> will not visually persist if you click "Add ISNI code" button afterwards
> or things like that.
> 
> I tested these known react-hydrate-resist tricks
> but they unfortunately did not work for ISNI codes:
> 
> https://github.com/jesus2099/konami-command/blob/a1dd018d84cecee965943dda19617a6807dcedc4/lib/SUPER.js#L163-L172
> https://github.com/loujine/musicbrainz-scripts/commit/d4c81839d8381df271e1c525cbe76e4131a49d3a

**Comment by jesus2099** [comment]
I put the PR on hold as I will try [my react-hydrate workaround](https://github.com/jesus2099/konami-command/blob/a1dd018d84cecee965943dda19617a6807dcedc4/lib/SUPER.js#L163-L172) once more, tomorrow. 
I think I made a mistake when I tried it on ISNI code!

<ins>No no, I did already test it well in 582de280ee6913a1527512a02462fadafba65333 and this react-hydrate workaround doesn't work for ISNI codes, indeed.
I reactivate the PR and there is that slight issue (on some browsers, not on Android Kiwi):
Newly inserted ISNI code (**automatically** from WD) visually disappears, if you click the **_Add ISNI code_** button without having interacted with the new code **manually** beforehand.</ins>

## Last update

Problem fixed by c2985419a15d1041bced5452803f8b4c63d3f8d1 thanks to https://nattaylor.com/blog/2022/userscripts-and-reactjs-forms/
The trick was to let the input event **bubbling up**!

> `bubbles: true`

**Comment by jesus2099** [comment]
Problem fixed by c2985419a15d1041bced5452803f8b4c63d3f8d1 thanks to https://nattaylor.com/blog/2022/userscripts-and-reactjs-forms/
The trick was to let the input event **bubbling up**!

> `bubbles: true`

**Comment by jesus2099** [comment]
Hi @Jerome-Roy / @loujine 
This PR is now ready, I think. 
It makes the userscript working, again. 
I hope you’re all right, in your cold country.

**Comment by loujine** [comment]
Not so cold when volcanoes wake up :)

Thanks for your PR, I'll try to take a look this week. I merged some simpler pull requests tonight, ping me if I broke something

**Comment by jesus2099** [comment]
I tried to analyse the merge conflict, please tell me if it's OK for you, @loujine. :)


Remaining conflict compare
==========================

Repo `master` branch:

```js
    const isniBlock = document.getElementById(
        'add-isni-code').parentElement.parentElement;
    const fields = isniBlock.getElementsByTagName('input');
    for (const input of fields) {
        existing_isni.push(input.value.split(' ').join(''));
    }
    existing_isni.splice(0, 1); // skip template
    if (existing_isni.includes(isni.split(' ').join(''))) {
        return;
    }
    if (existing_isni.length === 1 && existing_isni[0] === '') {
        document.getElementsByName('edit-artist.isni_codes.0')[0].value = isni;
```

Repo `master` branch:

```js
    const isni_fields = document.querySelectorAll('input[name^="edit-artist.isni_codes."]');
    for (const input of isni_fields) {
        if (input.value) {
            existing_isni.push(input.value.split(' ').join(''));
        }
    }
    if (existing_isni.length === 0) {
        (Object.getOwnPropertyDescriptor(Object.getPrototypeOf(isni_fields[0]), 'value').set).call(isni_fields[0], isni);
        isni_fields[0].dispatchEvent(new Event('input', {bubbles: true}));
        $('#newFields').append(
            $('<dt>', {'text': 'New ISNI code added:'})
        ).append(
            $('<dd>', {'text': isni}).css('color', 'green')
        );
```

Break out
=========


ISNI fields selector
--------------------

`master` branch:

```js
    const isniBlock = document.getElementById(
        'add-isni-code').parentElement.parentElement;
    const fields = isniBlock.getElementsByTagName('input');
```

`isniBlock` is not used anywhere else, later.

This PR branch:

```js
    const isni_fields = document.querySelectorAll('input[name^="edit-artist.isni_codes."]');
```

These are doing the same thing, tell me if it's OK to keep this version of the ISNI selector fix, @loujine?


Template
--------

Template no longer exists and we should remove the skip:

`master` branch:

```js
    existing_isni.splice(0, 1); // skip template
```

Removed by this PR. 


Inform the user of already existing ISNI
----------------------------------------

`master` branch does not inform the user:

```js
    if (existing_isni.includes(isni.split(' ').join(''))) {
        return;
    }
```

This PR informed when same ISNI is already set.


Inform the user of new ISNI set
-------------------------------

This PR branch:

```js
        $('#newFields').append(
            $('<dt>', {'text': 'New ISNI code added:'})
        ).append(
            $('<dd>', {'text': isni}).css('color', 'green')
        );
```

This PR now informs when the new ISNI is being set, like for other attribute changes.


Setting value so that it is not hidden later by react-hydrate
-------------------------------------------------------------

Repo `master` branch:

```js
        document.getElementsByName('edit-artist.isni_codes.0')[0].value = isni;
```

Repo `master` branch:

```js
        (Object.getOwnPropertyDescriptor(Object.getPrototypeOf(isni_fields[0]), 'value').set).call(isni_fields[0], isni);
        isni_fields[0].dispatchEvent(new Event('input', {bubbles: true}));
```

Now that pages are using react, it is needed to prevent display bugs (disappearing ISNI when giving Add ISNI button), this way.

**Comment by jesus2099** [comment]
I solved conflict, keeping my ***ISNI fields selector***.
I hope it's good for you, otherwise, I can amend last commit. :)

**Comment by jesus2099** [comment]
I'm glad to hear from you, again! :)

**Comment by loujine** [comment]
I tested quickly, looks good, thanks so much
The hydration fix looks like the one I needed in the common script last year

**Review by loujine — APPROVED** [review]

**Pull request merged**
