### PR TITLE
Show checkbox on newly attached MBID too

### PR DESCRIPTION
**Pull request by jesus2099**
Newly attached MBID appear as `<td><i><a...>Recording MBID</a></i></td>` instead of `<td><a...>Recording Title</a></td>`.

For some reason they were excluded from script.

I include them as one may need to merge those new recordings too.

Like here: https://acoustid.org/track/64422fbb-b0ec-426b-9c00-31118754944b

But maybe there are other legitimate cases where those MBID-only recordings should be excluded?
I don't use AcoustID much, please tell me.
I think it's only when they are disabled too, which is still covered by your `if (!tr.classList.contains('mbid-disabled'))`.

### CODE REVIEW

**Comment by jesus2099** [comment]
Oh I see why you did not show checkbox for italic MBID.

They don't always mean brand new recordings, they also often mean merged away recordings like https://acoustid.org/track/fc1a542d-4c52-43dd-9aab-e06173e40c10 where both grows are now the same merged recording.
I think I will add a check if only one recording fix ID found, to not launch the merge, because it will not work.

**Comment by loujine** [comment]
I thought links appearing as mbids were always obsolete, so I excluded them from merging. If you find a solution to ditinguish from new mbids, no problem to merge this PR of course.

**Comment by jesus2099** [comment]
Whoops, I closed this one by force pushing master branch for #33.
I don't mind that much.

**Comment by jesus2099** [comment]
I see more often MBID that I do need to merge rather than MBID that just redirect to a merged recording.

Probably because AcoustID server is [often late](https://community.metabrainz.org/t/acoustids-of-merged-recordings-are-not-listed-in-the-fingerprits-tab/664013/2?u=jesus2099), nowadays.

I think it should be benefical to reenable this.
Because even in the case where MBID is just a merged recording, it does not harm much (it will just redirect to another recording)...

It would be nice to distinguish them, though... it would require to call them each and see if MBID redirects or not...

**Comment by jesus2099** [comment]
I made a new version: #113

**Pull request closed without merging**
