### PR TITLE
Replace lodash with native code

### PR DESCRIPTION
**Pull request by reosarevok**
MB has dropped Lodash and this was causing issues. I only tested the Wikidata change directly, since I don't use the others, but I think this should work? Please do test it though :) 

I also changed the scripts to track the latest common file from github master rather than a fixed version in an external website (since without that the scripts would still be broken anyway until the external website gets changed). I can drop that one if you have a specific reason to prefer the existing way though!

### CODE REVIEW

**Comment by loujine** [comment]
LGTM
I will merge and check all scripts afterwards

Regarding the greasemonkey links, I think that's fine, I should probably completely remove my scripts there, I think there's no point to it now that my scripts are on github.

**Comment by loujine** [comment]
All scripts should be fixed now
Thanks so much reo <3

**Comment by translit** [comment]
Still broken for me. None of your scripts get displayed.

**Comment by loujine** [comment]
@translit : what version of the scripts do you have? what error message can you see in the console? If you have a too old version, the upgrade won't work. Reinstall the scripts instead.
And please open a new ticket if needed, don't comment on that closed ticket

**Pull request merged**
